{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [70.0, 70.0, 1100.0, 720.0],
    "default_fontsize": 12.0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "boxes": [
      { "box": { "id": "c1", "maxclass": "comment", "text": "Acquario Boids — netreceive v2, NO oscparse. Python sends plain Max messages on UDP 7401.", "patching_rect": [30.0, 20.0, 700.0, 20.0] } },
      { "box": { "id": "lb", "maxclass": "newobj", "text": "loadbang", "patching_rect": [30.0, 55.0, 70.0, 22.0] } },
      { "box": { "id": "mf", "maxclass": "message", "text": "220.", "patching_rect": [115.0, 55.0, 50.0, 22.0] } },
      { "box": { "id": "ma", "maxclass": "message", "text": "0.10", "patching_rect": [180.0, 55.0, 50.0, 22.0] } },
      { "box": { "id": "nr", "maxclass": "newobj", "text": "netreceive -u 7401", "patching_rect": [30.0, 100.0, 130.0, 22.0] } },
      { "box": { "id": "pr", "maxclass": "print", "text": "PLAIN_RAW_7401", "patching_rect": [180.0, 100.0, 130.0, 22.0] } },
      { "box": { "id": "rt", "maxclass": "newobj", "text": "route direct midi note rest descriptors controls section event", "patching_rect": [30.0, 145.0, 395.0, 22.0] } },
      { "box": { "id": "ud", "maxclass": "newobj", "text": "unpack f f f f f f f", "patching_rect": [30.0, 195.0, 175.0, 22.0] } },
      { "box": { "id": "c2", "maxclass": "comment", "text": "direct = mean_speed energy center_x center_y density spread density_fader", "patching_rect": [215.0, 195.0, 480.0, 20.0] } },
      { "box": { "id": "fs", "maxclass": "flonum", "patching_rect": [30.0, 240.0, 70.0, 22.0] } },
      { "box": { "id": "c3", "maxclass": "comment", "text": "mean_speed", "patching_rect": [105.0, 242.0, 90.0, 20.0] } },
      { "box": { "id": "ef", "maxclass": "newobj", "text": "expr 80. + ($f1 * 820.)", "patching_rect": [30.0, 275.0, 165.0, 22.0] } },
      { "box": { "id": "pf", "maxclass": "newobj", "text": "pack f 50", "patching_rect": [30.0, 310.0, 75.0, 22.0] } },
      { "box": { "id": "lf", "maxclass": "newobj", "text": "line~", "patching_rect": [30.0, 345.0, 55.0, 22.0] } },
      { "box": { "id": "cy", "maxclass": "newobj", "text": "cycle~", "patching_rect": [30.0, 380.0, 60.0, 22.0] } },
      { "box": { "id": "fe", "maxclass": "flonum", "patching_rect": [285.0, 240.0, 70.0, 22.0] } },
      { "box": { "id": "c4", "maxclass": "comment", "text": "energy", "patching_rect": [360.0, 242.0, 70.0, 20.0] } },
      { "box": { "id": "ea", "maxclass": "newobj", "text": "expr 0.03 + ($f1 * 0.27)", "patching_rect": [285.0, 275.0, 175.0, 22.0] } },
      { "box": { "id": "pa", "maxclass": "newobj", "text": "pack f 50", "patching_rect": [285.0, 310.0, 75.0, 22.0] } },
      { "box": { "id": "la", "maxclass": "newobj", "text": "line~", "patching_rect": [285.0, 345.0, 55.0, 22.0] } },
      { "box": { "id": "mul", "maxclass": "newobj", "text": "*~", "patching_rect": [30.0, 430.0, 40.0, 22.0] } },
      { "box": { "id": "dac", "maxclass": "ezdac~", "patching_rect": [30.0, 490.0, 45.0, 45.0] } },
      { "box": { "id": "c5", "maxclass": "comment", "text": "Lock patch Ctrl+E, click ezdac~. You should hear a default tone immediately; boids then modulate it.", "patching_rect": [90.0, 502.0, 650.0, 20.0] } },
      { "box": { "id": "um", "maxclass": "newobj", "text": "unpack i i i i i i", "patching_rect": [650.0, 195.0, 150.0, 22.0] } },
      { "box": { "id": "c6", "maxclass": "comment", "text": "midi = event_id midi_note velocity duration_ms layer_id section_id", "patching_rect": [810.0, 195.0, 260.0, 35.0] } },
      { "box": { "id": "mn", "maxclass": "newobj", "text": "makenote", "patching_rect": [680.0, 270.0, 70.0, 22.0] } },
      { "box": { "id": "no", "maxclass": "newobj", "text": "noteout", "patching_rect": [680.0, 310.0, 60.0, 22.0] } },
      { "box": { "id": "pm", "maxclass": "print", "text": "MIDI_EVENTS", "patching_rect": [650.0, 350.0, 100.0, 22.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["lb", 0], "destination": ["mf", 0] } },
      { "patchline": { "source": ["lb", 0], "destination": ["ma", 0] } },
      { "patchline": { "source": ["mf", 0], "destination": ["pf", 0] } },
      { "patchline": { "source": ["ma", 0], "destination": ["pa", 0] } },
      { "patchline": { "source": ["nr", 0], "destination": ["pr", 0] } },
      { "patchline": { "source": ["nr", 0], "destination": ["rt", 0] } },
      { "patchline": { "source": ["rt", 0], "destination": ["ud", 0] } },
      { "patchline": { "source": ["ud", 0], "destination": ["fs", 0] } },
      { "patchline": { "source": ["fs", 0], "destination": ["ef", 0] } },
      { "patchline": { "source": ["ef", 0], "destination": ["pf", 0] } },
      { "patchline": { "source": ["pf", 0], "destination": ["lf", 0] } },
      { "patchline": { "source": ["lf", 0], "destination": ["cy", 0] } },
      { "patchline": { "source": ["cy", 0], "destination": ["mul", 0] } },
      { "patchline": { "source": ["ud", 1], "destination": ["fe", 0] } },
      { "patchline": { "source": ["fe", 0], "destination": ["ea", 0] } },
      { "patchline": { "source": ["ea", 0], "destination": ["pa", 0] } },
      { "patchline": { "source": ["pa", 0], "destination": ["la", 0] } },
      { "patchline": { "source": ["la", 0], "destination": ["mul", 1] } },
      { "patchline": { "source": ["mul", 0], "destination": ["dac", 0] } },
      { "patchline": { "source": ["mul", 0], "destination": ["dac", 1] } },
      { "patchline": { "source": ["rt", 1], "destination": ["um", 0] } },
      { "patchline": { "source": ["rt", 1], "destination": ["pm", 0] } },
      { "patchline": { "source": ["um", 1], "destination": ["mn", 0] } },
      { "patchline": { "source": ["um", 2], "destination": ["mn", 1] } },
      { "patchline": { "source": ["um", 3], "destination": ["mn", 2] } },
      { "patchline": { "source": ["mn", 0], "destination": ["no", 0] } },
      { "patchline": { "source": ["mn", 1], "destination": ["no", 1] } }
    ]
  }
}
