{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [80.0, 80.0, 1050.0, 680.0],
    "bglocked": 0,
    "openinpresentation": 0,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "gridsnaponopen": 1,
    "objectsnaponopen": 1,
    "statusbarvisible": 2,
    "toolbarvisible": 1,
    "boxes": [
      { "box": { "id": "obj-1", "maxclass": "comment", "text": "Acquario Boids — sound preview. 1) Avvia python main.py  2) Accendi ezdac~", "patching_rect": [30.0, 20.0, 620.0, 20.0] } },
      { "box": { "id": "obj-2", "maxclass": "newobj", "text": "udpreceive 7400", "patching_rect": [30.0, 60.0, 110.0, 22.0] } },
      { "box": { "id": "obj-3", "maxclass": "newobj", "text": "oscparse", "patching_rect": [30.0, 95.0, 70.0, 22.0] } },
      { "box": { "id": "obj-4", "maxclass": "newobj", "text": "route aquarium music", "patching_rect": [30.0, 130.0, 150.0, 22.0] } },
      { "box": { "id": "obj-5", "maxclass": "newobj", "text": "route direct", "patching_rect": [30.0, 170.0, 90.0, 22.0] } },
      { "box": { "id": "obj-6", "maxclass": "newobj", "text": "unpack f f f f f f f", "patching_rect": [30.0, 210.0, 170.0, 22.0] } },
      { "box": { "id": "obj-7", "maxclass": "comment", "text": "/aquarium/direct: mean_speed energy center_x center_y density spread density_fader", "patching_rect": [210.0, 210.0, 520.0, 20.0] } },
      { "box": { "id": "obj-8", "maxclass": "flonum", "patching_rect": [30.0, 255.0, 70.0, 22.0] } },
      { "box": { "id": "obj-9", "maxclass": "comment", "text": "mean_speed -> frequency", "patching_rect": [105.0, 257.0, 150.0, 20.0] } },
      { "box": { "id": "obj-10", "maxclass": "newobj", "text": "scale 0. 1. 80. 900.", "patching_rect": [30.0, 290.0, 145.0, 22.0] } },
      { "box": { "id": "obj-11", "maxclass": "newobj", "text": "pack 0. 50", "patching_rect": [30.0, 325.0, 80.0, 22.0] } },
      { "box": { "id": "obj-12", "maxclass": "newobj", "text": "line~", "patching_rect": [30.0, 360.0, 55.0, 22.0] } },
      { "box": { "id": "obj-13", "maxclass": "newobj", "text": "cycle~", "patching_rect": [30.0, 395.0, 60.0, 22.0] } },
      { "box": { "id": "obj-14", "maxclass": "flonum", "patching_rect": [295.0, 255.0, 70.0, 22.0] } },
      { "box": { "id": "obj-15", "maxclass": "comment", "text": "energy -> amplitude", "patching_rect": [370.0, 257.0, 140.0, 20.0] } },
      { "box": { "id": "obj-16", "maxclass": "newobj", "text": "scale 0. 1. 0.02 0.30", "patching_rect": [295.0, 290.0, 160.0, 22.0] } },
      { "box": { "id": "obj-17", "maxclass": "newobj", "text": "pack 0. 50", "patching_rect": [295.0, 325.0, 80.0, 22.0] } },
      { "box": { "id": "obj-18", "maxclass": "newobj", "text": "line~", "patching_rect": [295.0, 360.0, 55.0, 22.0] } },
      { "box": { "id": "obj-19", "maxclass": "newobj", "text": "*~", "patching_rect": [30.0, 445.0, 40.0, 22.0] } },
      { "box": { "id": "obj-20", "maxclass": "ezdac~", "patching_rect": [30.0, 500.0, 45.0, 45.0] } },
      { "box": { "id": "obj-21", "maxclass": "comment", "text": "Accendi qui per sentire il drone controllato dai boids", "patching_rect": [85.0, 512.0, 330.0, 20.0] } },
      { "box": { "id": "obj-22", "maxclass": "newobj", "text": "route midi note rest", "patching_rect": [610.0, 170.0, 140.0, 22.0] } },
      { "box": { "id": "obj-23", "maxclass": "newobj", "text": "unpack i i i i i i", "patching_rect": [610.0, 210.0, 150.0, 22.0] } },
      { "box": { "id": "obj-24", "maxclass": "comment", "text": "/music/midi: event_id midi_note velocity duration_ms layer_id section_id", "patching_rect": [770.0, 212.0, 260.0, 35.0] } },
      { "box": { "id": "obj-25", "maxclass": "newobj", "text": "makenote", "patching_rect": [640.0, 285.0, 70.0, 22.0] } },
      { "box": { "id": "obj-26", "maxclass": "newobj", "text": "noteout", "patching_rect": [640.0, 325.0, 60.0, 22.0] } },
      { "box": { "id": "obj-27", "maxclass": "comment", "text": "Opzionale: MIDI out. Se non senti note MIDI, configura Options > MIDI Setup.", "patching_rect": [715.0, 318.0, 300.0, 35.0] } },
      { "box": { "id": "obj-28", "maxclass": "print", "text": "music_midi", "patching_rect": [610.0, 365.0, 90.0, 22.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["obj-2", 0], "destination": ["obj-3", 0] } },
      { "patchline": { "source": ["obj-3", 0], "destination": ["obj-4", 0] } },
      { "patchline": { "source": ["obj-4", 0], "destination": ["obj-5", 0] } },
      { "patchline": { "source": ["obj-5", 0], "destination": ["obj-6", 0] } },
      { "patchline": { "source": ["obj-6", 0], "destination": ["obj-8", 0] } },
      { "patchline": { "source": ["obj-8", 0], "destination": ["obj-10", 0] } },
      { "patchline": { "source": ["obj-10", 0], "destination": ["obj-11", 0] } },
      { "patchline": { "source": ["obj-11", 0], "destination": ["obj-12", 0] } },
      { "patchline": { "source": ["obj-12", 0], "destination": ["obj-13", 0] } },
      { "patchline": { "source": ["obj-13", 0], "destination": ["obj-19", 0] } },
      { "patchline": { "source": ["obj-6", 1], "destination": ["obj-14", 0] } },
      { "patchline": { "source": ["obj-14", 0], "destination": ["obj-16", 0] } },
      { "patchline": { "source": ["obj-16", 0], "destination": ["obj-17", 0] } },
      { "patchline": { "source": ["obj-17", 0], "destination": ["obj-18", 0] } },
      { "patchline": { "source": ["obj-18", 0], "destination": ["obj-19", 1] } },
      { "patchline": { "source": ["obj-19", 0], "destination": ["obj-20", 0] } },
      { "patchline": { "source": ["obj-19", 0], "destination": ["obj-20", 1] } },
      { "patchline": { "source": ["obj-4", 1], "destination": ["obj-22", 0] } },
      { "patchline": { "source": ["obj-22", 0], "destination": ["obj-23", 0] } },
      { "patchline": { "source": ["obj-22", 0], "destination": ["obj-28", 0] } },
      { "patchline": { "source": ["obj-23", 1], "destination": ["obj-25", 0] } },
      { "patchline": { "source": ["obj-23", 2], "destination": ["obj-25", 1] } },
      { "patchline": { "source": ["obj-23", 3], "destination": ["obj-25", 2] } },
      { "patchline": { "source": ["obj-25", 0], "destination": ["obj-26", 0] } },
      { "patchline": { "source": ["obj-25", 1], "destination": ["obj-26", 1] } }
    ]
  }
}
