{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [60.0, 60.0, 1200.0, 760.0],
    "bglocked": 0,
    "openinpresentation": 0,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "gridsnaponopen": 1,
    "objectsnaponopen": 1,
    "statusbarvisible": 2,
    "toolbarvisible": 1,
    "boxes": [
      { "box": { "id": "c-title", "maxclass": "comment", "text": "Acquario Boids — OSC symbolic patch. Uses udpreceive 7400, NO oscparse, NO /music/midi, NO noteout.", "patching_rect": [30.0, 20.0, 820.0, 20.0] } },
      { "box": { "id": "in", "maxclass": "newobj", "text": "udpreceive 7400", "patching_rect": [30.0, 60.0, 120.0, 22.0] } },
      { "box": { "id": "raw", "maxclass": "print", "text": "OSC_RAW_7400", "patching_rect": [170.0, 60.0, 120.0, 22.0] } },
      { "box": { "id": "route", "maxclass": "newobj", "text": "route /aquarium/direct /music/note /music/rest /aquarium/descriptors /aquarium/controls /aquarium/section /music/event", "patching_rect": [30.0, 105.0, 760.0, 22.0] } },

      { "box": { "id": "c-direct", "maxclass": "comment", "text": "/aquarium/direct = mean_speed energy center_x center_y density spread density_fader", "patching_rect": [30.0, 150.0, 620.0, 20.0] } },
      { "box": { "id": "print-direct", "maxclass": "print", "text": "OSC_DIRECT", "patching_rect": [690.0, 150.0, 95.0, 22.0] } },
      { "box": { "id": "d-speed", "maxclass": "message", "text": "$1", "patching_rect": [30.0, 190.0, 45.0, 22.0] } },
      { "box": { "id": "d-speed-label", "maxclass": "comment", "text": "$1 mean_speed -> drone frequency", "patching_rect": [85.0, 192.0, 220.0, 20.0] } },
      { "box": { "id": "drone-freq-expr", "maxclass": "newobj", "text": "expr 70. + ($f1 * 760.)", "patching_rect": [30.0, 225.0, 170.0, 22.0] } },
      { "box": { "id": "drone-freq-pack", "maxclass": "newobj", "text": "pack f 80", "patching_rect": [30.0, 260.0, 80.0, 22.0] } },
      { "box": { "id": "drone-freq-line", "maxclass": "newobj", "text": "line~", "patching_rect": [30.0, 295.0, 55.0, 22.0] } },
      { "box": { "id": "drone-osc", "maxclass": "newobj", "text": "cycle~", "patching_rect": [30.0, 330.0, 60.0, 22.0] } },

      { "box": { "id": "d-energy", "maxclass": "message", "text": "$2", "patching_rect": [320.0, 190.0, 45.0, 22.0] } },
      { "box": { "id": "d-energy-label", "maxclass": "comment", "text": "$2 energy -> drone amplitude", "patching_rect": [375.0, 192.0, 220.0, 20.0] } },
      { "box": { "id": "drone-amp-expr", "maxclass": "newobj", "text": "expr 0.02 + ($f1 * 0.22)", "patching_rect": [320.0, 225.0, 180.0, 22.0] } },
      { "box": { "id": "drone-amp-pack", "maxclass": "newobj", "text": "pack f 80", "patching_rect": [320.0, 260.0, 80.0, 22.0] } },
      { "box": { "id": "drone-amp-line", "maxclass": "newobj", "text": "line~", "patching_rect": [320.0, 295.0, 55.0, 22.0] } },
      { "box": { "id": "drone-mul", "maxclass": "newobj", "text": "*~", "patching_rect": [30.0, 380.0, 40.0, 22.0] } },

      { "box": { "id": "d-density", "maxclass": "message", "text": "$5", "patching_rect": [570.0, 190.0, 45.0, 22.0] } },
      { "box": { "id": "d-density-label", "maxclass": "comment", "text": "$5 density -> second OSC frequency", "patching_rect": [625.0, 192.0, 250.0, 20.0] } },
      { "box": { "id": "density-expr", "maxclass": "newobj", "text": "expr 110. + ($f1 * 330.)", "patching_rect": [570.0, 225.0, 175.0, 22.0] } },
      { "box": { "id": "density-pack", "maxclass": "newobj", "text": "pack f 80", "patching_rect": [570.0, 260.0, 80.0, 22.0] } },
      { "box": { "id": "density-line", "maxclass": "newobj", "text": "line~", "patching_rect": [570.0, 295.0, 55.0, 22.0] } },
      { "box": { "id": "density-osc", "maxclass": "newobj", "text": "cycle~", "patching_rect": [570.0, 330.0, 60.0, 22.0] } },
      { "box": { "id": "density-gain", "maxclass": "newobj", "text": "*~ 0.06", "patching_rect": [570.0, 380.0, 65.0, 22.0] } },

      { "box": { "id": "c-note", "maxclass": "comment", "text": "/music/note symbolic = event_id degree octave duration_beats velocity layer_id layer_name chord_degree section_id", "patching_rect": [30.0, 455.0, 760.0, 20.0] } },
      { "box": { "id": "print-note", "maxclass": "print", "text": "OSC_SYMBOLIC_NOTE", "patching_rect": [820.0, 455.0, 140.0, 22.0] } },
      { "box": { "id": "n-degree", "maxclass": "message", "text": "$2", "patching_rect": [30.0, 495.0, 45.0, 22.0] } },
      { "box": { "id": "n-degree-label", "maxclass": "comment", "text": "$2 degree", "patching_rect": [85.0, 497.0, 85.0, 20.0] } },
      { "box": { "id": "n-oct", "maxclass": "message", "text": "$3", "patching_rect": [180.0, 495.0, 45.0, 22.0] } },
      { "box": { "id": "n-oct-label", "maxclass": "comment", "text": "$3 octave", "patching_rect": [235.0, 497.0, 85.0, 20.0] } },
      { "box": { "id": "n-vel", "maxclass": "message", "text": "$5", "patching_rect": [330.0, 495.0, 45.0, 22.0] } },
      { "box": { "id": "n-vel-label", "maxclass": "comment", "text": "$5 velocity", "patching_rect": [385.0, 497.0, 90.0, 20.0] } },
      { "box": { "id": "n-chord", "maxclass": "message", "text": "$8", "patching_rect": [500.0, 495.0, 45.0, 22.0] } },
      { "box": { "id": "n-chord-label", "maxclass": "comment", "text": "$8 chord_degree", "patching_rect": [555.0, 497.0, 125.0, 20.0] } },

      { "box": { "id": "pitch-pak", "maxclass": "newobj", "text": "pak 0 0 0", "patching_rect": [30.0, 540.0, 90.0, 22.0] } },
      { "box": { "id": "pitch-expr", "maxclass": "newobj", "text": "expr 110. * exp(log(2.) * (($f1 + $f2 + ($f3 * 7.)) / 7.))", "patching_rect": [30.0, 575.0, 520.0, 22.0] } },
      { "box": { "id": "note-freq-pack", "maxclass": "newobj", "text": "pack f 5", "patching_rect": [30.0, 610.0, 75.0, 22.0] } },
      { "box": { "id": "note-freq-line", "maxclass": "newobj", "text": "line~", "patching_rect": [30.0, 645.0, 55.0, 22.0] } },
      { "box": { "id": "note-osc", "maxclass": "newobj", "text": "cycle~", "patching_rect": [30.0, 680.0, 60.0, 22.0] } },

      { "box": { "id": "vel-expr", "maxclass": "newobj", "text": "expr ($f1 / 127.) * 0.28", "patching_rect": [330.0, 540.0, 165.0, 22.0] } },
      { "box": { "id": "vel-pack", "maxclass": "newobj", "text": "pack f 8", "patching_rect": [330.0, 575.0, 70.0, 22.0] } },
      { "box": { "id": "vel-line", "maxclass": "newobj", "text": "line~", "patching_rect": [330.0, 610.0, 55.0, 22.0] } },
      { "box": { "id": "decay-delay", "maxclass": "newobj", "text": "delay 14", "patching_rect": [430.0, 575.0, 65.0, 22.0] } },
      { "box": { "id": "decay-msg", "maxclass": "message", "text": "0. 180", "patching_rect": [430.0, 610.0, 60.0, 22.0] } },
      { "box": { "id": "note-mul", "maxclass": "newobj", "text": "*~", "patching_rect": [30.0, 715.0, 40.0, 22.0] } },

      { "box": { "id": "mix1", "maxclass": "newobj", "text": "+~", "patching_rect": [840.0, 380.0, 40.0, 22.0] } },
      { "box": { "id": "mix2", "maxclass": "newobj", "text": "+~", "patching_rect": [840.0, 715.0, 40.0, 22.0] } },
      { "box": { "id": "master", "maxclass": "newobj", "text": "*~ 0.75", "patching_rect": [930.0, 545.0, 60.0, 22.0] } },
      { "box": { "id": "dac", "maxclass": "ezdac~", "patching_rect": [1030.0, 535.0, 45.0, 45.0] } },
      { "box": { "id": "c-dac", "maxclass": "comment", "text": "Lock patch (Ctrl+E), click ezdac~. This patch ignores /music/midi and uses /music/note symbolic OSC.", "patching_rect": [825.0, 600.0, 360.0, 35.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["in", 0], "destination": ["raw", 0] } },
      { "patchline": { "source": ["in", 0], "destination": ["route", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["print-direct", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["d-speed", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["d-energy", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["d-density", 0] } },
      { "patchline": { "source": ["d-speed", 0], "destination": ["drone-freq-expr", 0] } },
      { "patchline": { "source": ["drone-freq-expr", 0], "destination": ["drone-freq-pack", 0] } },
      { "patchline": { "source": ["drone-freq-pack", 0], "destination": ["drone-freq-line", 0] } },
      { "patchline": { "source": ["drone-freq-line", 0], "destination": ["drone-osc", 0] } },
      { "patchline": { "source": ["drone-osc", 0], "destination": ["drone-mul", 0] } },
      { "patchline": { "source": ["d-energy", 0], "destination": ["drone-amp-expr", 0] } },
      { "patchline": { "source": ["drone-amp-expr", 0], "destination": ["drone-amp-pack", 0] } },
      { "patchline": { "source": ["drone-amp-pack", 0], "destination": ["drone-amp-line", 0] } },
      { "patchline": { "source": ["drone-amp-line", 0], "destination": ["drone-mul", 1] } },
      { "patchline": { "source": ["d-density", 0], "destination": ["density-expr", 0] } },
      { "patchline": { "source": ["density-expr", 0], "destination": ["density-pack", 0] } },
      { "patchline": { "source": ["density-pack", 0], "destination": ["density-line", 0] } },
      { "patchline": { "source": ["density-line", 0], "destination": ["density-osc", 0] } },
      { "patchline": { "source": ["density-osc", 0], "destination": ["density-gain", 0] } },
      { "patchline": { "source": ["drone-mul", 0], "destination": ["mix1", 0] } },
      { "patchline": { "source": ["density-gain", 0], "destination": ["mix1", 1] } },
      { "patchline": { "source": ["route", 1], "destination": ["print-note", 0] } },
      { "patchline": { "source": ["route", 1], "destination": ["n-degree", 0] } },
      { "patchline": { "source": ["route", 1], "destination": ["n-oct", 0] } },
      { "patchline": { "source": ["route", 1], "destination": ["n-vel", 0] } },
      { "patchline": { "source": ["route", 1], "destination": ["n-chord", 0] } },
      { "patchline": { "source": ["n-degree", 0], "destination": ["pitch-pak", 0] } },
      { "patchline": { "source": ["n-chord", 0], "destination": ["pitch-pak", 1] } },
      { "patchline": { "source": ["n-oct", 0], "destination": ["pitch-pak", 2] } },
      { "patchline": { "source": ["pitch-pak", 0], "destination": ["pitch-expr", 0] } },
      { "patchline": { "source": ["pitch-expr", 0], "destination": ["note-freq-pack", 0] } },
      { "patchline": { "source": ["note-freq-pack", 0], "destination": ["note-freq-line", 0] } },
      { "patchline": { "source": ["note-freq-line", 0], "destination": ["note-osc", 0] } },
      { "patchline": { "source": ["note-osc", 0], "destination": ["note-mul", 0] } },
      { "patchline": { "source": ["n-vel", 0], "destination": ["vel-expr", 0] } },
      { "patchline": { "source": ["vel-expr", 0], "destination": ["vel-pack", 0] } },
      { "patchline": { "source": ["vel-pack", 0], "destination": ["vel-line", 0] } },
      { "patchline": { "source": ["route", 1], "destination": ["decay-delay", 0] } },
      { "patchline": { "source": ["decay-delay", 0], "destination": ["decay-msg", 0] } },
      { "patchline": { "source": ["decay-msg", 0], "destination": ["vel-line", 0] } },
      { "patchline": { "source": ["vel-line", 0], "destination": ["note-mul", 1] } },
      { "patchline": { "source": ["mix1", 0], "destination": ["mix2", 0] } },
      { "patchline": { "source": ["note-mul", 0], "destination": ["mix2", 1] } },
      { "patchline": { "source": ["mix2", 0], "destination": ["master", 0] } },
      { "patchline": { "source": ["master", 0], "destination": ["dac", 0] } },
      { "patchline": { "source": ["master", 0], "destination": ["dac", 1] } }
    ]
  }
}
