{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [100.0, 100.0, 900.0, 520.0],
    "bglocked": 0,
    "openinpresentation": 0,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "gridsnaponopen": 1,
    "objectsnaponopen": 1,
    "statusbarvisible": 2,
    "toolbarvisible": 1,
    "lefttoolbarpinned": 0,
    "toptoolbarpinned": 0,
    "righttoolbarpinned": 0,
    "bottomtoolbarpinned": 0,
    "toolbars_unpinned_last_save": 0,
    "tallnewobj": 0,
    "boxanimatetime": 200,
    "enablehscroll": 1,
    "enablevscroll": 1,
    "devicewidth": 0.0,
    "description": "Receiver OSC per Acquario Boids",
    "digest": "",
    "tags": "",
    "style": "",
    "subpatcher_template": "",
    "boxes": [
      { "box": { "id": "obj-1", "maxclass": "comment", "text": "Acquario Boids OSC receiver — Python -> Max", "patching_rect": [30.0, 20.0, 360.0, 20.0] } },
      { "box": { "id": "obj-2", "maxclass": "newobj", "text": "udpreceive 7400", "patching_rect": [30.0, 60.0, 110.0, 22.0] } },
      { "box": { "id": "obj-3", "maxclass": "newobj", "text": "oscparse", "patching_rect": [30.0, 100.0, 70.0, 22.0] } },
      { "box": { "id": "obj-4", "maxclass": "newobj", "text": "route aquarium music", "patching_rect": [30.0, 140.0, 150.0, 22.0] } },
      { "box": { "id": "obj-5", "maxclass": "newobj", "text": "route descriptors direct controls section descriptor", "patching_rect": [30.0, 190.0, 310.0, 22.0] } },
      { "box": { "id": "obj-6", "maxclass": "newobj", "text": "route event note rest", "patching_rect": [430.0, 190.0, 140.0, 22.0] } },
      { "box": { "id": "obj-7", "maxclass": "print", "text": "descriptors", "patching_rect": [30.0, 245.0, 90.0, 22.0] } },
      { "box": { "id": "obj-8", "maxclass": "print", "text": "direct", "patching_rect": [145.0, 245.0, 70.0, 22.0] } },
      { "box": { "id": "obj-9", "maxclass": "print", "text": "controls", "patching_rect": [235.0, 245.0, 80.0, 22.0] } },
      { "box": { "id": "obj-10", "maxclass": "print", "text": "section", "patching_rect": [335.0, 245.0, 80.0, 22.0] } },
      { "box": { "id": "obj-11", "maxclass": "print", "text": "single_descriptor", "patching_rect": [30.0, 285.0, 120.0, 22.0] } },
      { "box": { "id": "obj-12", "maxclass": "print", "text": "music_event", "patching_rect": [430.0, 245.0, 100.0, 22.0] } },
      { "box": { "id": "obj-13", "maxclass": "print", "text": "music_note", "patching_rect": [550.0, 245.0, 100.0, 22.0] } },
      { "box": { "id": "obj-14", "maxclass": "print", "text": "music_rest", "patching_rect": [670.0, 245.0, 100.0, 22.0] } },
      { "box": { "id": "obj-15", "maxclass": "comment", "text": "Per convertire note: midi = root + scale[(degree + chord_degree) % 7] + 12*octave", "patching_rect": [30.0, 345.0, 620.0, 20.0] } },
      { "box": { "id": "obj-16", "maxclass": "comment", "text": "Messaggi: /aquarium/direct per modulazione immediata; /music/note per eventi simbolici.", "patching_rect": [30.0, 375.0, 620.0, 20.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["obj-2", 0], "destination": ["obj-3", 0] } },
      { "patchline": { "source": ["obj-3", 0], "destination": ["obj-4", 0] } },
      { "patchline": { "source": ["obj-4", 0], "destination": ["obj-5", 0] } },
      { "patchline": { "source": ["obj-4", 1], "destination": ["obj-6", 0] } },
      { "patchline": { "source": ["obj-5", 0], "destination": ["obj-7", 0] } },
      { "patchline": { "source": ["obj-5", 1], "destination": ["obj-8", 0] } },
      { "patchline": { "source": ["obj-5", 2], "destination": ["obj-9", 0] } },
      { "patchline": { "source": ["obj-5", 3], "destination": ["obj-10", 0] } },
      { "patchline": { "source": ["obj-5", 4], "destination": ["obj-11", 0] } },
      { "patchline": { "source": ["obj-6", 0], "destination": ["obj-12", 0] } },
      { "patchline": { "source": ["obj-6", 1], "destination": ["obj-13", 0] } },
      { "patchline": { "source": ["obj-6", 2], "destination": ["obj-14", 0] } }
    ]
  }
}
