{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [60.0, 60.0, 1200.0, 760.0],
    "bglocked": 0,
    "openinpresentation": 0,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "gridsnaponopen": 1,
    "objectsnaponopen": 1,
    "statusbarvisible": 2,
    "toolbarvisible": 1,
    "boxes": [
      { "box": { "id": "c-title", "maxclass": "comment", "text": "Acquario Boids — mapped patch WITHOUT oscparse and WITHOUT unpack. Use with Python main.py. Port 7401.", "patching_rect": [30.0, 20.0, 760.0, 20.0] } },
      { "box": { "id": "in", "maxclass": "newobj", "text": "netreceive -u 7401", "patching_rect": [30.0, 60.0, 130.0, 22.0] } },
      { "box": { "id": "raw", "maxclass": "print", "text": "RAW_7401", "patching_rect": [180.0, 60.0, 90.0, 22.0] } },
      { "box": { "id": "route", "maxclass": "newobj", "text": "route direct midi note rest descriptors controls section event", "patching_rect": [30.0, 105.0, 400.0, 22.0] } },

      { "box": { "id": "c-direct", "maxclass": "comment", "text": "DIRECT continuous mapping: direct mean_speed energy center_x center_y density spread density_fader", "patching_rect": [30.0, 150.0, 650.0, 20.0] } },
      { "box": { "id": "d-print", "maxclass": "print", "text": "DIRECT_LIST", "patching_rect": [700.0, 150.0, 95.0, 22.0] } },
      { "box": { "id": "d1", "maxclass": "message", "text": "$1", "patching_rect": [30.0, 190.0, 45.0, 22.0] } },
      { "box": { "id": "d1-label", "maxclass": "comment", "text": "$1 mean_speed -> drone frequency", "patching_rect": [85.0, 192.0, 210.0, 20.0] } },
      { "box": { "id": "freq-expr", "maxclass": "newobj", "text": "expr 70. + ($f1 * 760.)", "patching_rect": [30.0, 225.0, 165.0, 22.0] } },
      { "box": { "id": "freq-pack", "maxclass": "newobj", "text": "pack f 80", "patching_rect": [30.0, 260.0, 80.0, 22.0] } },
      { "box": { "id": "freq-line", "maxclass": "newobj", "text": "line~", "patching_rect": [30.0, 295.0, 55.0, 22.0] } },
      { "box": { "id": "drone-osc", "maxclass": "newobj", "text": "cycle~", "patching_rect": [30.0, 330.0, 60.0, 22.0] } },

      { "box": { "id": "d2", "maxclass": "message", "text": "$2", "patching_rect": [320.0, 190.0, 45.0, 22.0] } },
      { "box": { "id": "d2-label", "maxclass": "comment", "text": "$2 energy -> drone amplitude", "patching_rect": [375.0, 192.0, 210.0, 20.0] } },
      { "box": { "id": "amp-expr", "maxclass": "newobj", "text": "expr 0.02 + ($f1 * 0.22)", "patching_rect": [320.0, 225.0, 175.0, 22.0] } },
      { "box": { "id": "amp-pack", "maxclass": "newobj", "text": "pack f 80", "patching_rect": [320.0, 260.0, 80.0, 22.0] } },
      { "box": { "id": "amp-line", "maxclass": "newobj", "text": "line~", "patching_rect": [320.0, 295.0, 55.0, 22.0] } },
      { "box": { "id": "drone-mul", "maxclass": "newobj", "text": "*~", "patching_rect": [30.0, 380.0, 40.0, 22.0] } },

      { "box": { "id": "d5", "maxclass": "message", "text": "$5", "patching_rect": [570.0, 190.0, 45.0, 22.0] } },
      { "box": { "id": "d5-label", "maxclass": "comment", "text": "$5 density -> second oscillator frequency", "patching_rect": [625.0, 192.0, 260.0, 20.0] } },
      { "box": { "id": "dens-expr", "maxclass": "newobj", "text": "expr 110. + ($f1 * 330.)", "patching_rect": [570.0, 225.0, 170.0, 22.0] } },
      { "box": { "id": "dens-pack", "maxclass": "newobj", "text": "pack f 80", "patching_rect": [570.0, 260.0, 80.0, 22.0] } },
      { "box": { "id": "dens-line", "maxclass": "newobj", "text": "line~", "patching_rect": [570.0, 295.0, 55.0, 22.0] } },
      { "box": { "id": "dens-osc", "maxclass": "newobj", "text": "cycle~", "patching_rect": [570.0, 330.0, 60.0, 22.0] } },
      { "box": { "id": "dens-gain", "maxclass": "newobj", "text": "*~ 0.06", "patching_rect": [570.0, 380.0, 60.0, 22.0] } },

      { "box": { "id": "c-midi", "maxclass": "comment", "text": "MIDI/Markov events: midi event_id midi_note velocity duration_ms layer_id section_id. Here they trigger short internal blips.", "patching_rect": [30.0, 455.0, 760.0, 20.0] } },
      { "box": { "id": "m-print", "maxclass": "print", "text": "MIDI_LIST", "patching_rect": [700.0, 455.0, 90.0, 22.0] } },
      { "box": { "id": "m2", "maxclass": "message", "text": "$2", "patching_rect": [30.0, 495.0, 45.0, 22.0] } },
      { "box": { "id": "m2-label", "maxclass": "comment", "text": "$2 midi_note -> blip pitch", "patching_rect": [85.0, 497.0, 190.0, 20.0] } },
      { "box": { "id": "mtof", "maxclass": "newobj", "text": "mtof", "patching_rect": [30.0, 530.0, 45.0, 22.0] } },
      { "box": { "id": "blip-pack", "maxclass": "newobj", "text": "pack f 5", "patching_rect": [30.0, 565.0, 75.0, 22.0] } },
      { "box": { "id": "blip-fline", "maxclass": "newobj", "text": "line~", "patching_rect": [30.0, 600.0, 55.0, 22.0] } },
      { "box": { "id": "blip-osc", "maxclass": "newobj", "text": "cycle~", "patching_rect": [30.0, 635.0, 60.0, 22.0] } },

      { "box": { "id": "m3", "maxclass": "message", "text": "$3", "patching_rect": [300.0, 495.0, 45.0, 22.0] } },
      { "box": { "id": "m3-label", "maxclass": "comment", "text": "$3 velocity -> blip amplitude", "patching_rect": [355.0, 497.0, 210.0, 20.0] } },
      { "box": { "id": "vel-expr", "maxclass": "newobj", "text": "expr ($f1 / 127.) * 0.28", "patching_rect": [300.0, 530.0, 165.0, 22.0] } },
      { "box": { "id": "vel-pack", "maxclass": "newobj", "text": "pack f 8", "patching_rect": [300.0, 565.0, 70.0, 22.0] } },
      { "box": { "id": "vel-line", "maxclass": "newobj", "text": "line~", "patching_rect": [300.0, 600.0, 55.0, 22.0] } },
      { "box": { "id": "decay-delay", "maxclass": "newobj", "text": "delay 12", "patching_rect": [390.0, 530.0, 65.0, 22.0] } },
      { "box": { "id": "decay-msg", "maxclass": "message", "text": "0. 180", "patching_rect": [390.0, 565.0, 60.0, 22.0] } },
      { "box": { "id": "blip-mul", "maxclass": "newobj", "text": "*~", "patching_rect": [30.0, 680.0, 40.0, 22.0] } },

      { "box": { "id": "mix1", "maxclass": "newobj", "text": "+~", "patching_rect": [820.0, 390.0, 40.0, 22.0] } },
      { "box": { "id": "mix2", "maxclass": "newobj", "text": "+~", "patching_rect": [820.0, 680.0, 40.0, 22.0] } },
      { "box": { "id": "master", "maxclass": "newobj", "text": "*~ 0.75", "patching_rect": [900.0, 535.0, 60.0, 22.0] } },
      { "box": { "id": "dac", "maxclass": "ezdac~", "patching_rect": [1000.0, 525.0, 45.0, 45.0] } },
      { "box": { "id": "c-dac", "maxclass": "comment", "text": "Lock patch (Ctrl+E) and click ezdac~. Watch RAW_7401 / DIRECT_LIST / MIDI_LIST in Max Console.", "patching_rect": [840.0, 585.0, 330.0, 35.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["in", 0], "destination": ["raw", 0] } },
      { "patchline": { "source": ["in", 0], "destination": ["route", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["d-print", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["d1", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["d2", 0] } },
      { "patchline": { "source": ["route", 0], "destination": ["d5", 0] } },
      { "patchline": { "source": ["d1", 0], "destination": ["freq-expr", 0] } },
      { "patchline": { "source": ["freq-expr", 0], "destination": ["freq-pack", 0] } },
      { "patchline": { "source": ["freq-pack", 0], "destination": ["freq-line", 0] } },
      { "patchline": { "source": ["freq-line", 0], "destination": ["drone-osc", 0] } },
      { "patchline": { "source": ["drone-osc", 0], "destination": ["drone-mul", 0] } },
      { "patchline": { "source": ["d2", 0], "destination": ["amp-expr", 0] } },
      { "patchline": { "source": ["amp-expr", 0], "destination": ["amp-pack", 0] } },
      { "patchline": { "source": ["amp-pack", 0], "destination": ["amp-line", 0] } },
      { "patchline": { "source": ["amp-line", 0], "destination": ["drone-mul", 1] } },
      { "patchline": { "source": ["d5", 0], "destination": ["dens-expr", 0] } },
      { "patchline": { "source": ["dens-expr", 0], "destination": ["dens-pack", 0] } },
      { "patchline": { "source": ["dens-pack", 0], "destination": ["dens-line", 0] } },
      { "patchline": { "source": ["dens-line", 0], "destination": ["dens-osc", 0] } },
      { "patchline": { "source": ["dens-osc", 0], "destination": ["dens-gain", 0] } },
      { "patchline": { "source": ["drone-mul", 0], "destination": ["mix1", 0] } },
      { "patchline": { "source": ["dens-gain", 0], "destination": ["mix1", 1] } },
      { "patchline": { "source": ["route", 1], "destination": ["m-print", 0] } },
      { "patchline": { "source": ["route", 1], "destination": ["m2", 0] } },
      { "patchline": { "source": ["route", 1], "destination": ["m3", 0] } },
      { "patchline": { "source": ["m2", 0], "destination": ["mtof", 0] } },
      { "patchline": { "source": ["mtof", 0], "destination": ["blip-pack", 0] } },
      { "patchline": { "source": ["blip-pack", 0], "destination": ["blip-fline", 0] } },
      { "patchline": { "source": ["blip-fline", 0], "destination": ["blip-osc", 0] } },
      { "patchline": { "source": ["m3", 0], "destination": ["vel-expr", 0] } },
      { "patchline": { "source": ["vel-expr", 0], "destination": ["vel-pack", 0] } },
      { "patchline": { "source": ["vel-pack", 0], "destination": ["vel-line", 0] } },
      { "patchline": { "source": ["route", 1], "destination": ["decay-delay", 0] } },
      { "patchline": { "source": ["decay-delay", 0], "destination": ["decay-msg", 0] } },
      { "patchline": { "source": ["decay-msg", 0], "destination": ["vel-line", 0] } },
      { "patchline": { "source": ["blip-osc", 0], "destination": ["blip-mul", 0] } },
      { "patchline": { "source": ["vel-line", 0], "destination": ["blip-mul", 1] } },
      { "patchline": { "source": ["mix1", 0], "destination": ["mix2", 0] } },
      { "patchline": { "source": ["blip-mul", 0], "destination": ["mix2", 1] } },
      { "patchline": { "source": ["mix2", 0], "destination": ["master", 0] } },
      { "patchline": { "source": ["master", 0], "destination": ["dac", 0] } },
      { "patchline": { "source": ["master", 0], "destination": ["dac", 1] } }
    ]
  }
}
