{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [80.0, 80.0, 1050.0, 680.0],
    "bglocked": 0,
    "openinpresentation": 0,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "gridsnaponopen": 1,
    "objectsnaponopen": 1,
    "statusbarvisible": 2,
    "toolbarvisible": 1,
    "boxes": [
      { "box": { "id": "obj-1", "maxclass": "comment", "text": "Acquario Boids — Max fallback WITHOUT oscparse. Uses plain UDP on port 7401.", "patching_rect": [30.0, 20.0, 650.0, 20.0] } },
      { "box": { "id": "obj-2", "maxclass": "newobj", "text": "netreceive -u 7401", "patching_rect": [30.0, 60.0, 125.0, 22.0] } },
      { "box": { "id": "obj-3", "maxclass": "newobj", "text": "route direct midi note rest descriptors controls section event", "patching_rect": [30.0, 100.0, 385.0, 22.0] } },
      { "box": { "id": "obj-4", "maxclass": "newobj", "text": "unpack f f f f f f f", "patching_rect": [30.0, 150.0, 170.0, 22.0] } },
      { "box": { "id": "obj-5", "maxclass": "comment", "text": "direct = mean_speed energy center_x center_y density spread density_fader", "patching_rect": [210.0, 150.0, 500.0, 20.0] } },
      { "box": { "id": "obj-6", "maxclass": "flonum", "patching_rect": [30.0, 195.0, 70.0, 22.0] } },
      { "box": { "id": "obj-7", "maxclass": "comment", "text": "mean_speed", "patching_rect": [105.0, 197.0, 90.0, 20.0] } },
      { "box": { "id": "obj-8", "maxclass": "newobj", "text": "scale 0. 1. 80. 900.", "patching_rect": [30.0, 230.0, 145.0, 22.0] } },
      { "box": { "id": "obj-9", "maxclass": "newobj", "text": "pack 0. 50", "patching_rect": [30.0, 265.0, 80.0, 22.0] } },
      { "box": { "id": "obj-10", "maxclass": "newobj", "text": "line~", "patching_rect": [30.0, 300.0, 55.0, 22.0] } },
      { "box": { "id": "obj-11", "maxclass": "newobj", "text": "cycle~", "patching_rect": [30.0, 335.0, 60.0, 22.0] } },
      { "box": { "id": "obj-12", "maxclass": "flonum", "patching_rect": [285.0, 195.0, 70.0, 22.0] } },
      { "box": { "id": "obj-13", "maxclass": "comment", "text": "energy", "patching_rect": [360.0, 197.0, 70.0, 20.0] } },
      { "box": { "id": "obj-14", "maxclass": "newobj", "text": "scale 0. 1. 0.02 0.30", "patching_rect": [285.0, 230.0, 160.0, 22.0] } },
      { "box": { "id": "obj-15", "maxclass": "newobj", "text": "pack 0. 50", "patching_rect": [285.0, 265.0, 80.0, 22.0] } },
      { "box": { "id": "obj-16", "maxclass": "newobj", "text": "line~", "patching_rect": [285.0, 300.0, 55.0, 22.0] } },
      { "box": { "id": "obj-17", "maxclass": "newobj", "text": "*~", "patching_rect": [30.0, 390.0, 40.0, 22.0] } },
      { "box": { "id": "obj-18", "maxclass": "ezdac~", "patching_rect": [30.0, 450.0, 45.0, 45.0] } },
      { "box": { "id": "obj-19", "maxclass": "comment", "text": "Click ezdac~ after locking patch (Ctrl+E). This drone should sound immediately if data arrives.", "patching_rect": [90.0, 462.0, 560.0, 20.0] } },
      { "box": { "id": "obj-20", "maxclass": "newobj", "text": "unpack i i i i i i", "patching_rect": [610.0, 150.0, 150.0, 22.0] } },
      { "box": { "id": "obj-21", "maxclass": "comment", "text": "midi = event_id midi_note velocity duration_ms layer_id section_id", "patching_rect": [770.0, 150.0, 260.0, 35.0] } },
      { "box": { "id": "obj-22", "maxclass": "newobj", "text": "makenote", "patching_rect": [640.0, 225.0, 70.0, 22.0] } },
      { "box": { "id": "obj-23", "maxclass": "newobj", "text": "noteout", "patching_rect": [640.0, 265.0, 60.0, 22.0] } },
      { "box": { "id": "obj-24", "maxclass": "print", "text": "plain_midi", "patching_rect": [610.0, 310.0, 90.0, 22.0] } },
      { "box": { "id": "obj-25", "maxclass": "print", "text": "plain_note", "patching_rect": [720.0, 310.0, 90.0, 22.0] } },
      { "box": { "id": "obj-26", "maxclass": "print", "text": "plain_rest", "patching_rect": [830.0, 310.0, 90.0, 22.0] } },
      { "box": { "id": "obj-27", "maxclass": "print", "text": "plain_raw", "patching_rect": [30.0, 545.0, 90.0, 22.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["obj-2", 0], "destination": ["obj-3", 0] } },
      { "patchline": { "source": ["obj-2", 0], "destination": ["obj-27", 0] } },
      { "patchline": { "source": ["obj-3", 0], "destination": ["obj-4", 0] } },
      { "patchline": { "source": ["obj-4", 0], "destination": ["obj-6", 0] } },
      { "patchline": { "source": ["obj-6", 0], "destination": ["obj-8", 0] } },
      { "patchline": { "source": ["obj-8", 0], "destination": ["obj-9", 0] } },
      { "patchline": { "source": ["obj-9", 0], "destination": ["obj-10", 0] } },
      { "patchline": { "source": ["obj-10", 0], "destination": ["obj-11", 0] } },
      { "patchline": { "source": ["obj-11", 0], "destination": ["obj-17", 0] } },
      { "patchline": { "source": ["obj-4", 1], "destination": ["obj-12", 0] } },
      { "patchline": { "source": ["obj-12", 0], "destination": ["obj-14", 0] } },
      { "patchline": { "source": ["obj-14", 0], "destination": ["obj-15", 0] } },
      { "patchline": { "source": ["obj-15", 0], "destination": ["obj-16", 0] } },
      { "patchline": { "source": ["obj-16", 0], "destination": ["obj-17", 1] } },
      { "patchline": { "source": ["obj-17", 0], "destination": ["obj-18", 0] } },
      { "patchline": { "source": ["obj-17", 0], "destination": ["obj-18", 1] } },
      { "patchline": { "source": ["obj-3", 1], "destination": ["obj-20", 0] } },
      { "patchline": { "source": ["obj-3", 1], "destination": ["obj-24", 0] } },
      { "patchline": { "source": ["obj-20", 1], "destination": ["obj-22", 0] } },
      { "patchline": { "source": ["obj-20", 2], "destination": ["obj-22", 1] } },
      { "patchline": { "source": ["obj-20", 3], "destination": ["obj-22", 2] } },
      { "patchline": { "source": ["obj-22", 0], "destination": ["obj-23", 0] } },
      { "patchline": { "source": ["obj-22", 1], "destination": ["obj-23", 1] } },
      { "patchline": { "source": ["obj-3", 2], "destination": ["obj-25", 0] } },
      { "patchline": { "source": ["obj-3", 3], "destination": ["obj-26", 0] } }
    ]
  }
}
