{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [90.0, 90.0, 1250.0, 780.0],
    "default_fontsize": 12.0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "boxes": [
      { "box": { "id": "title", "maxclass": "comment", "text": "Aquarium Markov v2 OSC Preview — usa udpreceive 7400, NON usa netreceive", "patching_rect": [30.0, 20.0, 760.0, 20.0] } },
      { "box": { "id": "help", "maxclass": "comment", "text": "Apri Python main.py. Questa patch riceve /markov/v2/note, /chord, /hit e li manda a noteout 1/2/3/4/10.", "patching_rect": [30.0, 45.0, 950.0, 20.0] } },
      { "box": { "id": "in", "maxclass": "newobj", "text": "udpreceive 7400", "patching_rect": [30.0, 85.0, 120.0, 22.0] } },
      { "box": { "id": "raw", "maxclass": "newobj", "text": "print OSC_RAW_7400", "patching_rect": [170.0, 85.0, 140.0, 22.0] } },
      { "box": { "id": "route_main", "maxclass": "newobj", "text": "route /markov/v2/note /markov/v2/chord /markov/v2/hit /aquarium/direct /aquarium/performance", "patching_rect": [30.0, 130.0, 660.0, 22.0] } },

      { "box": { "id": "p_note", "maxclass": "newobj", "text": "print MARKOV_V2_NOTE", "patching_rect": [30.0, 170.0, 160.0, 22.0] } },
      { "box": { "id": "p_chord", "maxclass": "newobj", "text": "print MARKOV_V2_CHORD", "patching_rect": [730.0, 170.0, 170.0, 22.0] } },
      { "box": { "id": "p_hit", "maxclass": "newobj", "text": "print MARKOV_V2_HIT", "patching_rect": [730.0, 470.0, 150.0, 22.0] } },
      { "box": { "id": "p_direct", "maxclass": "newobj", "text": "print AQUARIUM_DIRECT", "patching_rect": [520.0, 170.0, 160.0, 22.0] } },
      { "box": { "id": "p_perf", "maxclass": "newobj", "text": "print AQUARIUM_PERFORMANCE", "patching_rect": [520.0, 205.0, 200.0, 22.0] } },

      { "box": { "id": "note_route", "maxclass": "newobj", "text": "route bass lead keys", "patching_rect": [30.0, 215.0, 150.0, 22.0] } },
      { "box": { "id": "note_comment", "maxclass": "comment", "text": "note voice midi_note velocity duration_ms degree octave layer_id scene_id chord_degree event_id", "patching_rect": [30.0, 245.0, 520.0, 20.0] } },

      { "box": { "id": "un_bass", "maxclass": "newobj", "text": "unpack i i i i i i i i i", "patching_rect": [30.0, 280.0, 175.0, 22.0] } },
      { "box": { "id": "mk_bass", "maxclass": "newobj", "text": "makenote", "patching_rect": [30.0, 320.0, 70.0, 22.0] } },
      { "box": { "id": "out_bass", "maxclass": "newobj", "text": "noteout 1", "patching_rect": [30.0, 360.0, 70.0, 22.0] } },
      { "box": { "id": "lab_bass", "maxclass": "comment", "text": "bass -> noteout channel 1", "patching_rect": [115.0, 360.0, 180.0, 20.0] } },

      { "box": { "id": "un_lead", "maxclass": "newobj", "text": "unpack i i i i i i i i i", "patching_rect": [30.0, 405.0, 175.0, 22.0] } },
      { "box": { "id": "mk_lead", "maxclass": "newobj", "text": "makenote", "patching_rect": [30.0, 445.0, 70.0, 22.0] } },
      { "box": { "id": "out_lead", "maxclass": "newobj", "text": "noteout 2", "patching_rect": [30.0, 485.0, 70.0, 22.0] } },
      { "box": { "id": "lab_lead", "maxclass": "comment", "text": "lead -> noteout channel 2", "patching_rect": [115.0, 485.0, 180.0, 20.0] } },

      { "box": { "id": "un_keys", "maxclass": "newobj", "text": "unpack i i i i i i i i i", "patching_rect": [30.0, 530.0, 175.0, 22.0] } },
      { "box": { "id": "mk_keys", "maxclass": "newobj", "text": "makenote", "patching_rect": [30.0, 570.0, 70.0, 22.0] } },
      { "box": { "id": "out_keys", "maxclass": "newobj", "text": "noteout 3", "patching_rect": [30.0, 610.0, 70.0, 22.0] } },
      { "box": { "id": "lab_keys", "maxclass": "comment", "text": "keys -> noteout channel 3", "patching_rect": [115.0, 610.0, 180.0, 20.0] } },

      { "box": { "id": "un_chord", "maxclass": "newobj", "text": "unpack i i i i i i", "patching_rect": [730.0, 215.0, 135.0, 22.0] } },
      { "box": { "id": "mk_chord1", "maxclass": "newobj", "text": "makenote 58 1900", "patching_rect": [730.0, 265.0, 115.0, 22.0] } },
      { "box": { "id": "mk_chord2", "maxclass": "newobj", "text": "makenote 58 1900", "patching_rect": [730.0, 315.0, 115.0, 22.0] } },
      { "box": { "id": "mk_chord3", "maxclass": "newobj", "text": "makenote 58 1900", "patching_rect": [730.0, 365.0, 115.0, 22.0] } },
      { "box": { "id": "out_chord", "maxclass": "newobj", "text": "noteout 4", "patching_rect": [885.0, 315.0, 70.0, 22.0] } },
      { "box": { "id": "lab_chord", "maxclass": "comment", "text": "chord triad -> noteout channel 4", "patching_rect": [970.0, 315.0, 220.0, 20.0] } },

      { "box": { "id": "hit_route", "maxclass": "newobj", "text": "route grain glitch noise", "patching_rect": [730.0, 515.0, 165.0, 22.0] } },
      { "box": { "id": "hit_comment", "maxclass": "comment", "text": "hit voice sample_id velocity duration_ms scene_id event_id -> noteout channel 10", "patching_rect": [730.0, 545.0, 430.0, 20.0] } },

      { "box": { "id": "un_grain", "maxclass": "newobj", "text": "unpack i i i i i", "patching_rect": [730.0, 580.0, 115.0, 22.0] } },
      { "box": { "id": "expr_grain", "maxclass": "newobj", "text": "expr 72 + $i1", "patching_rect": [730.0, 615.0, 95.0, 22.0] } },
      { "box": { "id": "mk_grain", "maxclass": "newobj", "text": "makenote", "patching_rect": [730.0, 650.0, 70.0, 22.0] } },

      { "box": { "id": "un_glitch", "maxclass": "newobj", "text": "unpack i i i i i", "patching_rect": [870.0, 580.0, 115.0, 22.0] } },
      { "box": { "id": "expr_glitch", "maxclass": "newobj", "text": "expr 84 + $i1", "patching_rect": [870.0, 615.0, 95.0, 22.0] } },
      { "box": { "id": "mk_glitch", "maxclass": "newobj", "text": "makenote", "patching_rect": [870.0, 650.0, 70.0, 22.0] } },

      { "box": { "id": "un_noise", "maxclass": "newobj", "text": "unpack i i i i i", "patching_rect": [1010.0, 580.0, 115.0, 22.0] } },
      { "box": { "id": "expr_noise", "maxclass": "newobj", "text": "expr 36 + $i1", "patching_rect": [1010.0, 615.0, 95.0, 22.0] } },
      { "box": { "id": "mk_noise", "maxclass": "newobj", "text": "makenote", "patching_rect": [1010.0, 650.0, 70.0, 22.0] } },
      { "box": { "id": "out_hit", "maxclass": "newobj", "text": "noteout 10", "patching_rect": [870.0, 700.0, 80.0, 22.0] } },

      { "box": { "id": "footer", "maxclass": "comment", "text": "Se non senti: doppio click sui noteout e scegli una destinazione MIDI. Per test rapido prova Microsoft GS Wavetable Synth.", "patching_rect": [30.0, 720.0, 900.0, 20.0] } }
    ],
    "lines": [
      { "patchline": { "source": ["in", 0], "destination": ["raw", 0] } },
      { "patchline": { "source": ["in", 0], "destination": ["route_main", 0] } },
      { "patchline": { "source": ["route_main", 0], "destination": ["p_note", 0] } },
      { "patchline": { "source": ["route_main", 1], "destination": ["p_chord", 0] } },
      { "patchline": { "source": ["route_main", 2], "destination": ["p_hit", 0] } },
      { "patchline": { "source": ["route_main", 3], "destination": ["p_direct", 0] } },
      { "patchline": { "source": ["route_main", 4], "destination": ["p_perf", 0] } },
      { "patchline": { "source": ["route_main", 0], "destination": ["note_route", 0] } },
      { "patchline": { "source": ["note_route", 0], "destination": ["un_bass", 0] } },
      { "patchline": { "source": ["note_route", 1], "destination": ["un_lead", 0] } },
      { "patchline": { "source": ["note_route", 2], "destination": ["un_keys", 0] } },
      { "patchline": { "source": ["un_bass", 0], "destination": ["mk_bass", 0] } },
      { "patchline": { "source": ["un_bass", 1], "destination": ["mk_bass", 1] } },
      { "patchline": { "source": ["un_bass", 2], "destination": ["mk_bass", 2] } },
      { "patchline": { "source": ["mk_bass", 0], "destination": ["out_bass", 0] } },
      { "patchline": { "source": ["mk_bass", 1], "destination": ["out_bass", 1] } },
      { "patchline": { "source": ["un_lead", 0], "destination": ["mk_lead", 0] } },
      { "patchline": { "source": ["un_lead", 1], "destination": ["mk_lead", 1] } },
      { "patchline": { "source": ["un_lead", 2], "destination": ["mk_lead", 2] } },
      { "patchline": { "source": ["mk_lead", 0], "destination": ["out_lead", 0] } },
      { "patchline": { "source": ["mk_lead", 1], "destination": ["out_lead", 1] } },
      { "patchline": { "source": ["un_keys", 0], "destination": ["mk_keys", 0] } },
      { "patchline": { "source": ["un_keys", 1], "destination": ["mk_keys", 1] } },
      { "patchline": { "source": ["un_keys", 2], "destination": ["mk_keys", 2] } },
      { "patchline": { "source": ["mk_keys", 0], "destination": ["out_keys", 0] } },
      { "patchline": { "source": ["mk_keys", 1], "destination": ["out_keys", 1] } },
      { "patchline": { "source": ["route_main", 1], "destination": ["un_chord", 0] } },
      { "patchline": { "source": ["un_chord", 0], "destination": ["mk_chord1", 0] } },
      { "patchline": { "source": ["un_chord", 1], "destination": ["mk_chord2", 0] } },
      { "patchline": { "source": ["un_chord", 2], "destination": ["mk_chord3", 0] } },
      { "patchline": { "source": ["mk_chord1", 0], "destination": ["out_chord", 0] } },
      { "patchline": { "source": ["mk_chord1", 1], "destination": ["out_chord", 1] } },
      { "patchline": { "source": ["mk_chord2", 0], "destination": ["out_chord", 0] } },
      { "patchline": { "source": ["mk_chord2", 1], "destination": ["out_chord", 1] } },
      { "patchline": { "source": ["mk_chord3", 0], "destination": ["out_chord", 0] } },
      { "patchline": { "source": ["mk_chord3", 1], "destination": ["out_chord", 1] } },
      { "patchline": { "source": ["route_main", 2], "destination": ["hit_route", 0] } },
      { "patchline": { "source": ["hit_route", 0], "destination": ["un_grain", 0] } },
      { "patchline": { "source": ["hit_route", 1], "destination": ["un_glitch", 0] } },
      { "patchline": { "source": ["hit_route", 2], "destination": ["un_noise", 0] } },
      { "patchline": { "source": ["un_grain", 0], "destination": ["expr_grain", 0] } },
      { "patchline": { "source": ["expr_grain", 0], "destination": ["mk_grain", 0] } },
      { "patchline": { "source": ["un_grain", 1], "destination": ["mk_grain", 1] } },
      { "patchline": { "source": ["un_grain", 2], "destination": ["mk_grain", 2] } },
      { "patchline": { "source": ["mk_grain", 0], "destination": ["out_hit", 0] } },
      { "patchline": { "source": ["mk_grain", 1], "destination": ["out_hit", 1] } },
      { "patchline": { "source": ["un_glitch", 0], "destination": ["expr_glitch", 0] } },
      { "patchline": { "source": ["expr_glitch", 0], "destination": ["mk_glitch", 0] } },
      { "patchline": { "source": ["un_glitch", 1], "destination": ["mk_glitch", 1] } },
      { "patchline": { "source": ["un_glitch", 2], "destination": ["mk_glitch", 2] } },
      { "patchline": { "source": ["mk_glitch", 0], "destination": ["out_hit", 0] } },
      { "patchline": { "source": ["mk_glitch", 1], "destination": ["out_hit", 1] } },
      { "patchline": { "source": ["un_noise", 0], "destination": ["expr_noise", 0] } },
      { "patchline": { "source": ["expr_noise", 0], "destination": ["mk_noise", 0] } },
      { "patchline": { "source": ["un_noise", 1], "destination": ["mk_noise", 1] } },
      { "patchline": { "source": ["un_noise", 2], "destination": ["mk_noise", 2] } },
      { "patchline": { "source": ["mk_noise", 0], "destination": ["out_hit", 0] } },
      { "patchline": { "source": ["mk_noise", 1], "destination": ["out_hit", 1] } }
    ]
  }
}
